maintainer       "Dell, Inc."
maintainer_email "Paul_Webster@Dell.com"
license          "All rights reserved"
description      "Installs and configures the baseline hadoop cluster component (HDFS/Map Reduce)"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "1.0"
recipe           "hadoop::default", "Installs hadoop base libraries and configuration."
recipe           "hadoop::jobtracker", "Installs the job tracker package."
recipe           "hadoop::masternamenode", "Installs the master name node package and prepares the file system."
recipe           "hadoop::secondarynamenode", "Installs the secondary name node package and prepares the file system."
recipe           "hadoop::slavenode", "Installs the slave node and task tracker packages and prepares the file system."
recipe           "hadoop::edgenode", "Installs the edge node and task tracker packages and prepares the file system."
recipe           "hadoop::hive-sql", "Ensure that mysql is running and hive can log into it."
recipe           "hadoop::hive", "Installs the Hive package."
recipe           "hadoop::flume", "Installs the Base Flume package."
recipe           "hadoop::flume-masternode", "Installs the Flume master node package."
recipe           "hadoop::flume-slavenode", "Installs the Flume slave node package."
